name: markovstates
channels: 
  - conda-forge
dependencies:
  - python >= 3.13
  - numpy
  - pandas
  - hmmlearn
  - matplotlib
  - scipy
  - pip
  - pip:
    - openmeteo_requests
    - requests_cache 
    - retry_requests